package com.hy300.keystone.app;

import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;

/** Talks to the shell-privileged helper (helper/Helper.java) on 127.0.0.1:38300. */
final class HelperClient {
    static final String BASE = "http://127.0.0.1:38300";
    /** Generated by the app on each start and handed to the helper when the app launches it. */
    static volatile String token = "";

    static boolean health() {
        try {
            return new JSONObject(call("GET", "/health", null, 2000).body).optBoolean("ok");
        } catch (Exception e) {
            return false;
        }
    }

    /** True when a helper is running and accepts our token (not one left over from an earlier launch). */
    static boolean accepted() {
        try {
            return call("GET", "/state", null, 2000).code == 200;
        } catch (Exception e) {
            return false;
        }
    }

    static final class Result {
        final int code;
        final String body;
        Result(int code, String body) { this.code = code; this.body = body; }
    }

    static Result call(String method, String path, String body, int timeoutMs) throws Exception {
        HttpURLConnection c = (HttpURLConnection) new URL(BASE + path).openConnection();
        c.setRequestMethod(method);
        c.setConnectTimeout(2000);
        c.setReadTimeout(timeoutMs);
        c.setRequestProperty("X-Token", token);
        if (body != null) {
            c.setDoOutput(true);
            c.setRequestProperty("Content-Type", "application/json");
            try (OutputStream o = c.getOutputStream()) { o.write(body.getBytes(StandardCharsets.UTF_8)); }
        }
        int code = c.getResponseCode();
        InputStream in = code >= 400 ? c.getErrorStream() : c.getInputStream();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        if (in != null) {
            byte[] buf = new byte[4096];
            for (int n; (n = in.read(buf)) > 0; ) out.write(buf, 0, n);
            in.close();
        }
        c.disconnect();
        return new Result(code, out.toString("UTF-8"));
    }

    private HelperClient() {}
}
